
baguette:
    server:
        id: server_id
    api_endpoint: https://app-572ff0d7-ba03-444b-8156-d9c8d804b9a9.cleverapps.io

qr:
    before_line: ""
    after_line: ""
    big: false
    inverse: false

texts:
    prompt: |
        Authenticate at
        -----------------
        {url}
        -----------------
        {qr}
        Hit enter when you authenticate

